// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { CounterGame, CounterGameData, CounterGameTableId } from "./tables/CounterGame.sol";
import { AccountFactorySingleton, AccountFactorySingletonTableId } from "./tables/AccountFactorySingleton.sol";
