// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAccountSystem {
  function createAccount() external returns (uint32);

  function linkAccount(address _account) external returns (bytes32 _accountId);
}
