// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAccountSystem {
  function setAccountFactory(address _accountFactory) external;

  function createAccount() external returns (address _account);

  function ownerAccounts(address _owner, uint256 _index) external view returns (address);
}
