// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IAccount } from "./../../account/Account.sol";

interface IAccountSystem {
  function setAccountFactory(address _accountFactory) external;

  function createAccount() external returns (address _account);

  function ownerAccounts(address _owner, uint256 _index) external view returns (address);

  function getAuthController() external view returns (address);

  function getAccountSystemAddress() external view returns (address _accountSystemAddress);

  function auth(
    IAccount.PermissionData calldata _permissionData,
    bytes calldata _signature
  ) external returns (uint256 _permissionId);

  function execute(uint256 _permissionId, bytes calldata _data) external returns (bytes memory _returnData);
}
