// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IAccount } from "./../../account/Account.sol";

interface ICounterGameSystem {
  function checkAndUpdateLimit(
    uint256 _permissionId,
    IAccount.PermissionData calldata _permissionData
  ) external returns (bool _isAllowed);

  function createGame(address _player1, address _player2) external returns (bytes32 _gameId);

  function acceptGame(bytes32 _gameId) external returns (bool _playerConsent);

  function increment(bytes32 _gameId) external returns (bool _playerWon);
}
