// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IAccount } from "./../../account/Account.sol";

interface ICounterGameSystem {
  function getPermissionData(bytes calldata _data) external view returns (bytes memory _limitData);

  function checkAndUpdateLimit(
    uint256 _permissionId,
    IAccount.PermissionData calldata _permissionData,
    bytes calldata _data
  ) external returns (bool _allowed);

  function createGame(address _player1, address _player2) external returns (bytes32 _gameId);

  function acceptGame(bytes32 _gameId) external returns (bool _playerConsent);

  function increment(bytes32 _gameId, string calldata _message) external returns (bool _playerWon);
}
